# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 #clona o código na máquina virtual criada acima
    - name: Set up JDK 17 #configurando a JDK
      uses: actions/setup-java@v4 #comando de setup da JDK
      with:
        java-version: '17' #versão da JDK
        distribution: 'temurin' #distribuição da versão do JAVA (pode ser qualquer um)
        cache: maven 
    - name: Build with Maven 
      run: |
        cd Projeto_Perguntas_Maven 
        mvn clean install -DskipTests
